name: flutter_vibe_template
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_size_text: ^3.0.0

  # UI & Icons
  cupertino_icons: ^1.0.8

  # Routing
  go_router: ^14.6.2

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Storage
  shared_preferences: ^2.3.3

  # Theming
  flex_color_scheme: ^8.0.2

  # UI Components
  oktoast: ^3.4.0
  skeletonizer: ^1.4.2

  # Networking
  dio: ^5.7.0

  # Image Caching
  cached_network_image: ^3.4.1

  # Authentication
  supabase_flutter: ^2.8.0
  sign_in_with_apple: ^6.1.2
  crypto: ^3.0.6

  # URL Launcher
  url_launcher: ^6.3.1

  # Renaming
  rename_app: ^1.6.5

  # Native Splash
  flutter_native_splash: ^2.4.6

  # Freezed
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  collection: ^1.19.1
  flutter_launcher_icons: ^0.14.4

  flutter_dotenv: ^5.2.1

  # RevenuCat
  purchases_flutter: ^9.1.0
  purchases_ui_flutter: ^9.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Code Generation
  build_runner: ^2.5.4
  riverpod_generator: ^2.6.2

  # Linting
  flutter_lints: ^5.0.0

  # Change App Package Name
  change_app_package_name: ^1.4.0
  freezed: ^3.1.0
  json_serializable: ^6.9.5

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true

  # Assets
  assets:
    - assets/images/
    - assets/icons/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
